[phases.setup]
nixPkgs = ["python310", "pip", "postgresql_16.dev", "gcc"]

[phases.build]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "uvicorn api.app.main:app --host 0.0.0.0 --port 8000"