[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql_16.dev"]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = ". /opt/venv/bin/activate && uvicorn api.app.main:app --host 0.0.0.0 --port 8000"
